### ISSUE TITLE
Streamline Maxmind licensing

### ISSUE THREAD

**Issue by kidmose** [aau-network-security/richkit#102]
When Maxmind (the company providing the resources backing some of the functions in `lookup`) changed their API from anonymous HTTP download to a HTTP download where a (free) license key is required, a quick fix was implemented so that the key was read from the `MAXMIND_LICENSE_KEY` environment variable.

This is lacking at least the following:

 

- [x]  Documentation on where and how to obtain the license
- [x] Documentation on how to configure the license
- [x] Handling of missing license, e.g. such that all other parts of `richkit`, in particular `richkit.lookup`, still is functional when the key is not configured.
- [x] relevant test cases for the step above

And there might be more to add.

**Comment by mrtrkmn** [comment]
@kidmose, when I read `Handling of missing license ... `, I understood that, the module should NOT be functional  if there is no configured `MAXMIND_LICENSE_KEY` ? 
Am I understand correctly ?

**Comment by kidmose** [comment]
>  functional if there is no configured `MAXMIND_LICENSE_KEY` ?
> Am I understand correctly ?

I foresee scenarios where a license key is not available, e.g. because the maxmind db functionality isn't used, so the users want bother with registering for the license (or can not agree to the terms, wont pay, etc.)

I such scenarios I think all other parts of richkit - those not depending on on a maxmind license - should still function 100 %. This includes other parts of lookup as well.

When there is a license, everything should just run :)

When there is no license key configured;
 * `from richkit import lookup` should run, perhaps printing a warning that the maxmind db functionality is not loaded due to missing license, 
 * and everything in `lookup.*` that does not need the license should work as normal. 
 * The bits that require the license should raise some exception (e.g. RuntimeError) with some useful information (Ideally a link to the documentation)

This is my understanding of how to handle this in a pythonic way, if this doesn't make sense or appear wrong, let me know!

Random thoughts that might be useful, but not necesarilly:
 * This is perhaps a good time to move everything `MaxMindDB` form `lookup/util.py` into its own submodule (e.g. `lookup/maxmind.py`)
 * Maybe this can be handled elegantly by having having `maxmind.py` throw and exception when loaded if there is no license and then in `lookup/__ini__.py` do some;
```
try:
    import MaxMindDB
except ImportError:
    MaxMindDB = None
...
# and then only define MaxMindDB related methods in __init__.py ...
if MaxMindDB:
   def ....
```
or perhaps the calls to e.g. `lookup.get_country(....)` should just raise exceptions on their own..

**Comment by kidmose** [comment]
Does that long story address your question, @mrturkmen06 ? :)

**Comment by mrtrkmn** [comment]
Yeah it is addressed the question that I was referring. 

Thanks for the explanation, @kidmose.

I have created related pull request #122
