### ISSUE TITLE
is_outdated function fails 

### ISSUE THREAD

**Issue by mrtrkmn** [aau-network-security/richkit#119]
- in `test_util.py` file is_outdated function is failing, needs to be fixed.

**Comment by kidmose** [comment]
Some more details, like a link to the fail would be nice :)
It looks like it works on most recent [`develop` test](https://github.com/aau-network-security/richkit/runs/544605349#step:5:14)
**but** I do recall some error as I was flying through your PRs (Great work btw!), so there is indeed an issue to be handled.
