### ISSUE TITLE
define git hooks for better git branch names

### ISSUE THREAD

**Issue by mrturkmen06** [aau-network-security/richkit#29]
There should some name conventions in order to get out from a situation where everything is messed up. This issue could be closed by creating customised  git hooks which might run on server and client side.

- New branches should be created from master branch
- If there is no issue which points your dev intention, first create issue and define your intention
- There should not be branch-to-branch (other than master) pull requests at least for time being. 
- The name of branches should match with the issues that the project has.
- Branch names should contain issue number at the end otherwise that should NOT be accepted
- A proper  length of branch name should be between 18 and 25. 
- Example : 
         - For issue #4, the ideal branch name could be [add-more-sources-#4](https://github.com/aau-network-security/domain-analysis-toolkit/tree/add-more-sources-%234)

**Comment by mrturkmen06** [comment]
https://stackoverflow.com/questions/22100581/github-server-side-git-hooks-i-e-pre-commit-and-post-commit :(

**Comment by kidmose** [comment]
With Travis you have `$TRAVIS_PULL_REQUEST_BRANCH` available.
Suppose  you have you hooks as shell scripts in e.g. `.githooks/test_branch_name.sh`.
Then on travis I believe you can test with this command: 

    ./.githooks/test_branch_name.sh --name=$TRAVIS_PULL_REQUEST_BRANCH

Or not?

https://graysonkoonce.com/getting-the-current-branch-name-during-a-pull-request-in-travis-ci/
