### ISSUE TITLE
https://richkit.readthedocs.io/en/latest/ not available

### ISSUE THREAD

**Issue by kidmose** [aau-network-security/richkit#51]
I was hoping to access the richkit documentation at https://richkit.readthedocs.io/en/latest/ but I get an error:

        \          SORRY            /
         \                         /
          \    This page does     /
           ]   not exist yet.    [    ,'|
           ]                     [   /  |
           ]___               ___[ ,'   |
           ]  ]\             /[  [ |:   |
           ]  ] \           / [  [ |:   |
           ]  ]  ]         [  [  [ |:   |
           ]  ]  ]__     __[  [  [ |:   |
           ]  ]  ] ]\ _ /[ [  [  [ |:   |
           ]  ]  ] ] (#) [ [  [  [ :===='
           ]  ]  ]_].nHn.[_[  [  [
           ]  ]  ]  HHHHH. [  [  [
           ]  ] /   `HH("N  \ [  [
           ]__]/     HHH  "  \[__[
           ]         NNN         [
           ]         N/"         [
           ]         N H         [
          /          N            \
         /           q,            \
        /                           \

Could be related to the need to do a release, as mentioned in #6   ?

Also the build seems to have failed: https://readthedocs.org/projects/richkit/builds/

**Comment by mrturkmen06** [comment]
closed it is up.
