### ISSUE TITLE
Publish documenation on https://readthedocs.org/

### ISSUE THREAD

**Issue by kidmose** [aau-network-security/richkit#6]
In order to build extend reach, I suggest the set up the continous delivery of the documentation to https://readthedocs.org/

**Comment by mrturkmen06** [comment]
related webhook added to project and project has been converted into open source project.

**Comment by mrturkmen06** [comment]
It is available here https://richkit.readthedocs.io/en/enable-docs-6/  however there are some misleading information which were  not updated when we changed name from dat > richkit.

**Comment by mrturkmen06** [comment]
webhooks have already been configured, so when we have release it will be published on readthedocs page.
