### ISSUE TITLE
Handle URLVoid changing number of blacklists

### ISSUE THREAD

**Issue by kidmose** [aau-network-security/richkit#77]
URLVoid appears to have changed the number of blacklists , leading to failed test:

https://github.com/aau-network-security/richkit/pull/71/checks?check_run_id=452081551#step:6:23

```
____________________ URLVoidTestCase.test_blacklist_status _____________________

self = <richkit.test.retrieve.test_urlvoid.URLVoidTestCase testMethod=test_blacklist_status>

    def test_blacklist_status(self):
        for k, v in self.test_urls.items():
            instance = URLVoid(k)
>           assert instance.blacklist_status() == v["blacklist_status"]
E           AssertionError: assert '0/34' == '0/36'
E             - 0/34
E             ?    ^
E             + 0/36
E             ?    ^

richkit/test/retrieve/test_urlvoid.py:79: AssertionError
```
We need to make the code and tests to be robust to such changes as we have seen them introduce noise before (E.g. #70 )

**Comment by kidmose** [comment]
We are testing against a live API and that is not optimal, because then you are likely to run into problems exactly like this:
The number of blacklists that this API checks against appears to change over time, thus the result returned from the API is changing, causing it to sometimes not match the expected output for the test, causing a test failure, finally leading to inconsistent and not reproducible test results.

Some thoughts:

1. Running the test as is is bad because it is flapping between good and bad, disturbing workflows and reducing productivity
2. Marking as ExpectedFail has the same problems as above, because sometimes it works (flapping...)
3. Mark as Skip is a quick, temporary fix that will remove the problem, but we loose the testing
4. Implementing some isolated unit testing will remediate the problem, without loosing test coverage, being the best solution, but also takes more effort.

Other thoughts? 

I'm in obviously in favour of PRs doing no. 3 and no.. 4 :)

**Comment by mrturkmen06** [comment]
I could not see any disadvantages of just skipping `blacklist_status` [check](https://github.com/aau-network-security/richkit/blob/27ba8c6de0a32a3d1169b7aa2e60245fc28f94b1/richkit/test/retrieve/test_urlvoid.py#L76), since URLVoid might include additional services or might delete existing ones, there is no concurrent point of checking it statically. I may oversimplify it however, I really could not see point of it. If we dynamically fetch and replace it with a variable instead of putting it as [string](https://github.com/aau-network-security/richkit/blob/27ba8c6de0a32a3d1169b7aa2e60245fc28f94b1/richkit/test/retrieve/test_urlvoid.py#L10), then there will be no meaning of having that test case.

**Comment by mrturkmen06** [comment]
Here is what I propose by explaining the reason ; https://github.com/aau-network-security/richkit/pull/88. I could not image `isolated unit testing` for blacklist status check, and I do not think it is suitable for isolated unit testing.

**Comment by kidmose** [comment]
> I could not see any disadvantages of just skipping `blacklist_status` [check](https://github.com/aau-network-security/richkit/blob/27ba8c6de0a32a3d1169b7aa2e60245fc28f94b1/richkit/test/retrieve/test_urlvoid.py#L76), since URLVoid might include additional services or might delete existing ones, there is no concurrent point of checking it statically. I may oversimplify it however, I really could not see point of it. If we dynamically fetch and replace it with a variable instead of putting it as [string](https://github.com/aau-network-security/richkit/blob/27ba8c6de0a32a3d1169b7aa2e60245fc28f94b1/richkit/test/retrieve/test_urlvoid.py#L10), then there will be no meaning of having that test case.

I follow you point.
I'm thinking that if we decide to solve this by skipping it, then we might as well just delete the test code altogether...

Then we have code the we don't do regression testing on, which I think is also a challenge..

**Comment by kidmose** [comment]
@gianmarcomennecozzi  and I discussed this on skype this morning.
Another idea is to do some minimal parsing of the results; Instead of checking that `value_returned_from_function == "0/36"` then check that `re.match(r'\d*/\d*', value_returned_from_function) is not None`.

Then we test, and we only rely on the URLVoid API to the point that it returns a valid fraction (`<integer>/<integer>`). 

Does that make sense?

**Comment by mrturkmen06** [comment]
ok

**Comment by mrturkmen06** [comment]
Should we care number of blacklist cases ?  For instance, if the result is like `1/36`, then should test case fail or not ?

**Comment by mrturkmen06** [comment]
Actually, we are testing against facebook and google, so defining regex `re.match(r'[0]/\d*', value_returned_from_function)` would be ok, I think. What do you think @kidmose and @gianmarcomennecozzi ?

**Comment by kidmose** [comment]
Makes sense. 
I will be a problem if one of the test values suddenly become blacklisted, but I'm ok with that :)
(Although it seems that everything is getting a virus infection these days ;) )
