### ISSUE TITLE
Inconsistent test cases 

### ISSUE THREAD

**Issue by mrturkmen06** [aau-network-security/richkit#87]
It is quite weird to see failure and pass cases when you have same commit id. I have tried to merge update_docs branch into develop branch, although it was only containing doc's updates, it is failed. So, i recover the commit which was passed before, however when I recover it, github actions started to fail. There is something wrong either in github actions or in our test cases. Needs to be investigated. Here is the screen shot what I am trying to say : 

<img width="1007" alt="Screenshot 2020-03-15 at 21 19 17" src="https://user-images.githubusercontent.com/13614433/76707772-36318800-6703-11ea-9bb9-00a533bccb1b.png">

Does anyone has any idea about it ?

**Comment by kidmose** [comment]
Looking into this, it seems that it fails at this point:
https://github.com/aau-network-security/richkit/runs/509492012#step:5:29

This is another example of #77 so let discuss it over there.
