### ISSUE TITLE
Release error 

### ISSUE THREAD

**Issue by mrturkmen06** [aau-network-security/richkit#97]
Error on releasing new version to python package

<img width="858" alt="Screenshot 2020-03-17 at 23 07 38" src="https://user-images.githubusercontent.com/13614433/76897185-5187c900-68a4-11ea-8e30-d2676e745bcf.png">

I am checking it...

**Comment by mrturkmen06** [comment]
`GITHUB_TOKEN` has been changed with another token. Afterwards following error occurred. 
<img width="1086" alt="Screenshot 2020-03-19 at 14 20 17" src="https://user-images.githubusercontent.com/13614433/77062431-e990ca00-69ec-11ea-839f-730f5022f833.png">

For this particular problem, #100 pull request created as recommended on pypi website.

**Comment by mrtrkmn** [comment]
The problem was having a release which is deleted by me on pypi, I was thinking to overwrite on it, however it is not possible, therefore another release name added 1.1.1b0. Problem solved. 

New version released.
